Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'MicFly_Control')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('MicFly_Control', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
