Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'MicFly')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('MicFly', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
